package com.arbolesyazilim.esmaulhusna

object Constants {
    fun getNames(): ArrayList<Name>{
        val nameList = ArrayList<Name>()
        val name1 = Name(1, "الله","Allah","Eşi benzeri olmayan, Tek ilah, isimlerin sultanı",66,"Her türlü istek, tüm duaların kabul olması")
        nameList.add(name1)
        val name2 = Name(2, "الرحمن","Er-Rahmân","Tüm yaratılanlara merhamet eden",298,"Dünyada ve ahirette Allah'ın sevgisini kazanmak")
        nameList.add(name2)
        val name3 = Name(3, "الرحيم","Er-Rahim","Ahirette inananlara sonsuz ihsan, ikram ve lütufta bulunan",258,"Maddi ve manevi rızka nail olmak")
        nameList.add(name3)
        val name4 = Name(4, "الملك","El-Melik","Tüm evrenin sahibi, saltanatı ve mülkü sürekli olan",90,"Maddi ve manevi güçlü olmak, insanlara sözlerini anlatıp, dinletebilmek, emir sahibi olmak")
        nameList.add(name4)
        val name5 = Name(5, "القدّوس","El-Kuddüs","Tüm eksikliklerden uzak",170,"Maddi ve manevi her türlü temizlik, kalp temizliği, ruhi hastalıklardan iyileşmek")
        nameList.add(name5)
        val name6 = Name(6, "السلام","Es-Selam","Tüm tehlikelerden selamete çıkaran",131,"Korkulan her şeyden emin olmak ve esenliğe çıkmak")
        nameList.add(name6)
        val name7 = Name(7, "المؤمن","El-Mü'min","Koruyan, Güvenilen",137,"Güvende olma, güvenilir insan olma, kötü hastalıklara düşmemek")
        nameList.add(name7)
        val name8 = Name(8, "المهيْمن","El-Müheymin","Her şeyi gören ve gözeten",145,"İnsanlardan korunmak ve onların düşüncelerine akıl erdirebilmek")
        nameList.add(name8)
        val name9 = Name(9, "العزيز","El-Aziz","Her şeyin galibi ve izzet sahibi olan",94,"Düşmanlara galip gelmek")
        nameList.add(name9)
        val name10 = Name(10, "الجبّار","El-Cebbar"," Kudret sahibi olan",206,"İstek ve arzuların olması, insanların ve cinlerin şerrinden emin olmak")
        nameList.add(name10)
        val name11 = Name(11, "المتكبّر","El-Mütekebbir","Eşi benzeri olmayan büyüklükte olan",662,"İzzet, refah ve gerçek büyüklüğe erişmek, halk tarafından sevilmek")
        nameList.add(name11)
        val name12 = Name(12, "الخالق","El-Halık","Yaratan",731,"İşlerde üzüntü ve sıkıntıdan kurtulmak, başarılı olmak")
        nameList.add(name12)
        val name13 = Name(13, "البارئ","El-Bari","Kusursuz ve eksiksiz yaratan",214,"İşte başarılı olmak, maddi ve manevi sıkıntılardan kurtulmak")
        nameList.add(name13)
        val name14 = Name(14, "المصور","El-Musavvir","Tüm varlıklara şekil veren",336,"Maksat ve meramına ulaşmak ve ifade etmek, en zor işleri başarmak ve bir işte uzmanlaşmak")
        nameList.add(name14)
        val name15 = Name(15, "الغفّار","El-Gaffar","Mağfireti bol olan",1281,"Bağışlanmak ve günahlardan korunmak")
        nameList.add(name15)
        val name16 = Name(16, "القهّار","El-Kahhar","Her şeye hakim olan",306,"Zalimlerin ve din düşmanlarının kahrından kurtulmak")
        nameList.add(name16)
        val name17 = Name(17, "الوهّاب","El-Vehhab","Karşılıksız veren",14,"Sıkıntısız ve maddi açıdan rahat bir hayat sürmek")
        nameList.add(name17)
        val name18 = Name(18, "الرزّاق","El-Rezzak","Rızık veren",308,"Bol rızıklı bir ömür geçirmek")
        nameList.add(name18)
        val name19 = Name(19,"الفتّاح","El-Fettah","Dardan kurtaran",489,"Maddi ve manevi hayır kapılarının açılması, ticarette başarıya ulaşmak")
        nameList.add(name19)
        val name20 = Name(20, "العليم","El-Alim","Her şeyi bilen ve gören",150,"İlim zenginliği için")
        nameList.add(name20)
        val name21 = Name(21, "القابض","El-Kabıd","Dilediğini darlık verme gücü olan",903,"Zalimin zulmünden kurtulmak")
        nameList.add(name21)
        val name22= Name(22, "الباسط","El-Basıt"," İstediğine bolluk veren",72,"Rızkının genişlemesi ve bereketin artması")
        nameList.add(name22)
        val name23 = Name(23, "الخافض","El-Hafıd","Kafirleri alçaltan",1481,"Kötüden, kötülerden ve belalardan korunmak")
        nameList.add(name23)
        val name24 = Name(24, "الرافع","Er-Rafi"," İnananları yükselten",351,"İnsanlar içinde ve işinde yükselmek, tevazu sahibi olmak")
        nameList.add(name24)
        val name25 = Name(25, "المعز","El-Mu'ız","Aziz kılan, dilediğini yücelten",117,"Fakir ve zelillikten kurtulmak")
        nameList.add(name25)
        val name26 = Name(26, "المذل","El-Müzil","Dilediğini değersiz kılan",770,"Düşmanları zelil etmek")
        nameList.add(name26)
        val name27 = Name(27, "السميع","Es-Semi","Her şeyi duyan",180,"Duaların kabul olması")
        nameList.add(name27)
        val name28 = Name(28, "البصير","El-Basir","Her şeyi gören",112,"Acziyetin kalkması, basiretli olmak")
        nameList.add(name28)
        val name29 = Name(29, "الحكم","El-Hakem","Mutlak hakimiyete sahip olan",68,"Haklı davasını kazanmak, insanlar arasında hak ile hüküm vermek")
        nameList.add(name29)
        val name30 = Name(30, "العدل","El-Adl","Adil olan",104,"Adaletli olmak, haklı davayı kazanmak")
        nameList.add(name30)
        val name31 = Name(31, "اللطيف","El-Latif","Kullarına değer veren",129,"Dileklerin olması, kısmet ve rızkın artması")
        nameList.add(name31)
        val name32 = Name(32, "الخبير","El-Habir","Her şeyi bilen",812,"Hafıza ve idrakın genişlemesi")
        nameList.add(name32)
        val name33 = Name(33, "الحليم","El-Halim","Ceza verirken acele etmeyen",88,"Ahlak güzelliği ve yumuşak huylu olmak, hiddet ve sinirin gitmesi")
        nameList.add(name33)
        val name34 = Name(34, "العظيم","El-Azim","Yüce",1020,"Sözünün tesirli olması ve sözü dinlenir olmak")
        nameList.add(name34)
        val name35 = Name(35, "الغفور","El-Gafur","Affedici olan",1286,"Günahların affı ve kötü ahlaktan korunmak")
        nameList.add(name35)
        val name36 = Name(36, "الشكور","Eş-Şekur","Az amelde bile çok sevap veren",526,"Talihin açıklığı, kendine verilen nimetlerin şükrünü eda etmek, bol rızık için")
        nameList.add(name36)
        val name37 = Name(37, "العلي","El-Aliyy","Yüce",110,"Zilletten kurtulmak, ilim, derecelerin artması")
        nameList.add(name37)
        val name38 = Name(38, "الكبير","El-Kebir","Büyük olan",232,"Maddi ve manevi büyüklük, hürmet sahibi olmak")
        nameList.add(name38)
        val name39 = Name(39, "الحفيظ","El-Hafiz"," Koruyan",998,"Nefsinin ve malının korunması")
        nameList.add(name39)
        val name40 = Name(40, "المقيت","El-Mukit","Yaratılana rızkını veren",550,"Muhtaç olunan şeyi kazanmak ve rızık")
        nameList.add(name40)
        val name41 = Name(41, "الحسيب","El-Hasib","Hesaba alan",80,"Herkese karşı açık alınlı olmak")
        nameList.add(name41)
        val name42 = Name(42, "الجليل","El-Celil","Yüksek sıfatları olan",73,"Gerçek yüceliğe erişmek, zalim ve zorbayı zelil etmek")
        nameList.add(name42)
        val name43 = Name(43, "الكريم","El-Kerim"," İkram eden",270,"Bol rızık sahibi olmak, cömert olmak ve kolaylıklara nail olmak")
        nameList.add(name43)
        val name44 = Name(44, "الرقيب","Er-Rakib","Gören ve gözeten",312,"Her işte Allah'ın korumasında olmak, bunu hissetmek, hafızasının kuvvetlenmesi")
        nameList.add(name44)
        val name45 = Name(45, "المجيب","El-Mucib","Dualarını kabul eden",55,"Duaların kabul olunması")
        nameList.add(name45)
        val name46 = Name(46, "الواسع","El-Vasi","Rahmeti ve ilmi bol olan",137,"Ömür uzunluğu, sıhhat ve rızk genişliği için")
        nameList.add(name46)
        val name47 = Name(47, "الحكيم","El-Hakim","Hikmetli",78,"İlim ve hikmet sahibi olmak, uzağı görmek, hikmetli iş yapmak")
        nameList.add(name47)
        val name48 = Name(48, "الودود","El-Vedud","Kullarını seven",400,"İnsanların sevgisini kazanmak")
        nameList.add(name48)
        val name49 = Name(49, "المجيد","El-Mecid","Şerefi yüksek olan",3249,"İzzet ve şerefin artması")
        nameList.add(name49)
        val name50 = Name(50, "الباعث","El-Bais","Ölmüş olanları dirilten",573,"Kuvvetli irade ve alacaklarını almak")
        nameList.add(name50)
        val name51 = Name(51, "الشهيد","Eş-Şehid","Her zaman ve her yerde hazır olan",319,"Şehit olmak, heybetli olmak, halk arasında sevilmek")
        nameList.add(name51)
        val name52 = Name(52, "الحقّ","El-Hakk","Hakkı gösteren",108,"Sağlam bir imana ve doğru bir ibadet hayatına sahip olmak, başladığı işin sonunun gelmes")
        nameList.add(name52)
        val name53 = Name(53, "الوكيل","El-Vekil","Tevekkül edenlerin işlerini yoluna koyan",66,"Allah'tan her türlü yardım görmek")
        nameList.add(name53)
        val name54 = Name(54, "القويّ","El-Kaviyy"," Kudretli",116,"Kansızlık ve vücudun güçlü olması, zor işleri kolaylıkla halletmek")
        nameList.add(name54)
        val name55 = Name(55, "المتين","El-Metin","Güçlü olan",500,"Maddi ve manevi dayanıklı, sağlam ve iradeli olmak, hastalıklardan kurtulmak")
        nameList.add(name55)
        val name56 = Name(56, "الولي","El-Veliyy","İnananlara dost olan",	46,"Her işte Allah'ın yardımını istemek")
        nameList.add(name56)
        val name57 = Name(57, "الحميد","El-Hamid","Övgüye layık olan",	62,"Kazancın genişlemesi, Allah'ı çokça hamd etmek için yardım istemek")
        nameList.add(name57)
        val name58 = Name(58, "المحسي","El-Muhsi","Tüm varlıkların sayısını bilen",148,"Zekanın kuvvetli olması")
        nameList.add(name58)
        val name59 = Name(59, "المبدىء","El-Mübdi","Yoktan var eden",57,"Her işte muvaffak olmak, ummadığı yerden yardım gelmesi")
        nameList.add(name59)
        val name60 = Name(60, "المعيد","El-Muid","Öldüren ve sonrasında tekrar dirilten",124,"Elden kaçanı geri kazanmak, Allah'ın ahirette yeniden dirilme hakikatini ruhlarımıza duyurması")
        nameList.add(name60)
        val name61 = Name(61, "المحيي","El-Muhyi","Dirilten, can veren",68,"İşlerin başarılı olması, hastalıklardan kurtulmak")
        nameList.add(name61)
        val name62 = Name(62, "المميت","El-Mümit"," Öldüren",490,"Harama bakmamak, kötülüklerden vazgeçmek, devamlı ahireti hatırlamak")
        nameList.add(name62)
        val name63 = Name(63, "الحيّ","El-Hayy","Sonsuz hayata sahip olan",18,"Sözün tesirli olması, sözü dinlenir olmak")
        nameList.add(name63)
        val name64 = Name(64, "القيّوم","El-Kayyum","Varlıkları ayakta tutan",156,"Bütün işlerde yardımı Allah'tan beklemek, isteklere nail olmak, rızkın devamlı olması")
        nameList.add(name64)
        val name65 = Name(65, "الواجد","El-Vacid","istediğini her zaman bulan",196,"Aradığını ve kaybettiğini bulmak")
        nameList.add(name65)
        val name66 = Name(66, "الماجد","El-Macid","Şanı yüce olan",48,"Kazancın bolluğu ve şerefli bir hayat sahibi olmak")
        nameList.add(name66)
        val name67 = Name(67, "الواحد","El-Vahid","Eşi benzeri olmayan",19,"Kalbin uyanıklığı, isteklerin olması")
        nameList.add(name67)
        val name68 = Name(68, "الصمد","Es-Samed","Muhtaç olunan",134,"Hiç kimseye muhtaç olmamak")
        nameList.add(name68)
        val name69 = Name(69, "القادر","El-Kadir","Kudretli",305,"İstediğini yapmaya güç yetirme")
        nameList.add(name69)
        val name70 = Name(70, "المقتدر","El-Muktedir","Her şeye gücü yeten",744,"Her işte başarılı olmak")
        nameList.add(name70)
        val name71 = Name(71, "المقدّم","El-Mukaddim","İstediğini yükselten",184,"Daima yükselmek")
        nameList.add(name71)
        val name72 = Name(72, "المؤخّر","El-Muahhir","Dilediğini geri bırakan",847,"Kötü ve belalı birinin veya bir işin kendinden uzaklaşması")
        nameList.add(name72)
        val name73 = Name(73, "الأوّل","El-Evvel","Ezeli",37,"Her hayır işinde birinci olmak")
        nameList.add(name73)
        val name74 = Name(74, "الآخر","El-Ahir","Ebedi",801,"Ömrün uzun olması")
        nameList.add(name74)
        val name75 = Name(75, "الظاهر","El-Zahir","Varlığı açık olan",1106,"Her meselenin zuhuru, açıklığı, gizli olmaması")
        nameList.add(name75)
        val name76 = Name(76, "الباطن","El-Batın","Mahiyeti gizli olan",62,"Nefsi mutmain ve kalbi geniş olmak, iç rahatlığının artması")
        nameList.add(name76)
        val name77 = Name(77, "الوالي","El-Vali","Sahip olan",47,"Sözünün tesirli olması, insanların kendini sevmesi")
        nameList.add(name77)
        val name78 = Name(78, "المتعالِ","El-Müteali","Yüce",551,"İstediği makama gelmek ve yüceliğe ermek")
        nameList.add(name78)
        val name79 = Name(79, "البَرّ","El-Berr","İyiliği bol olan",202,"Her halukarda iyilik bulmak")
        nameList.add(name79)
        val name80 = Name(80, "التوّاب","Et-Tevvab","Günahları affeden",409,"Tevbelerin kabul olması")
        nameList.add(name80)
        val name81 = Name(81, "المنتقم","El-Müntekim","İntikam alan",630,"Zulüm ve fenalıklardan korunmak")
        nameList.add(name81)
        val name82 = Name(82, "العفو","El-Afüvv","Affeden",156,"Rızık bolluğu, kalp huzuru, affedilmek")
        nameList.add(name82)
        val name83 = Name(83, "الرؤوف","Er-Rauf","Merhametli olan",287,"Merhametinin artması, hiçbir varlıktan zarar görmemek")
        nameList.add(name83)
        val name84 = Name(84, "مالك الملك","Malik-ül Mülk","Tüm varlıkların sahibi olan",212,"Mal ve kazanca zarar gelmemesi, maddi ve manevi derecelerin artması")
        nameList.add(name84)
        val name85 = Name(85, "ذو الجلال والإكرام","Zül-Celali vel İkram","Celal sahibi",1100,"İşlerin kolay ve âsân olması, insanların kendini sevmesi")
        nameList.add(name85)
        val name86 = Name(86, "المقيت","El-Muksit","Adaletli olan",209,"Eşlerin arasını düzeltmek ve adaletli olmak")
        nameList.add(name86)
        val name87 = Name(87, "الجامع","El-Cami","Mahşer günü bir araya toplayan",114,"Küsleri barıştırmak ve hayırların birleşip toplanması")
        nameList.add(name87)
        val name88 = Name(88, "الغني","El-Ganiyy","Kimseye muhtaç olmayan",1060,"Gerçek zenginlik, servet ve geniş rızık, insanlar tarafından sevilmek")
        nameList.add(name88)
        val name89 = Name(89, "المغني","El-Mugni","Müstağni",1100,"Geçim genişliği, bol rızık ve zenginlik")
        nameList.add(name89)
        val name90 = Name(90, "المانع","El-Mani","İstediği bir şeye mani olan",161,"Kaza ve belalardan emin olmak")
        nameList.add(name90)
        val name91 = Name(91, "الضار","Ed-Darr","istediğine zarar veren",1001,"Zararlı kişilerden emin olmak ve onları Allah'a havale etmek")
        nameList.add(name91)
        val name92 = Name(92, "النافع","En-Nafi","istediğine fayda veren",201,"Hastalıklardan korunmak, şifa bulmak, zararlardan uzak durmak")
        nameList.add(name92)
        val name93 = Name(93, "النور","En-Nur","Alemi aydınlatan",256,"Doğruyu ve yanlışı görüp kalp nuruna sahip olmak")
        nameList.add(name93)
        val name94 = Name(94, "الهادي","Al-Hadi","Hidayet sahibi",400,"Doğru yolu bulmak ve çocuklarının serkeş olmaması")
        nameList.add(name94)
        val name95 = Name(95, "البديع","El-Bedi","Benzersiz yaratan",86,"Allah'ın yardımına nail olmak, maddi ve manevi güzellik için")
        nameList.add(name95)
        val name96 = Name(96, "الباقي","El-Baki","Ebedi",113,"Ömrün uzunluğu ve sağlıklı olmak")
        nameList.add(name96)
        val name97 = Name(97, "الوارث","El-Varis","Tüm her şeyin tek sahibi",707,"Uzun ömür, bol mal, şeref ve rızık sahibi olmak")
        nameList.add(name97)
        val name98 = Name(98, "الرشيد","Er-Reşid","Yol gösteren",514,"Güzel ahlak sahibi olmak, kötü alışkanlıklardan korunmak")
        nameList.add(name98)
        val name99 = Name(99, "الصبور","Es-Sabur","Ceza vermek için acele etmeyen",298,"Başladığı işi kolay bitirmek, sinirini yenmek ve sabırlı olmak")
        nameList.add(name99)
        return nameList

    }
}
